- name: install and run nginx
  hosts: all # bcoz dynamic inventory vundae anni servers ki connect avvamani
  become: yes # equal to -b in ad-hoc commands, getting the root access
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

